name: Add comment
on:
  issues:
    types:
      - reopened
      - opened
jobs:
  add-comment:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Add comment
        uses: actions/first-interaction@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          issue-message: |
            Thank you for finding an issue. We will look into this soon.
        
