name: Add comment
on:
  issues
  
jobs:
  address:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          issue-message: "Thank you for finding an issue. We will look into this soon."
