name: Commenting on pull request
on:
  pull_request:
    branches: [ "main" ]

jobs:
  comment_pr:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3

      - name: Accept PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            Thank you for contributing. Your request will be accepted soon. ![](https://www.google.com/imgres?imgurl=https%3A%2F%2Fthumbs.dreamstime.com%2Fz%2Fcontribute-d-word-pulled-up-team-giving-sharing-contribution-letters-working-together-donation-worthy-cause-47609276.jpg&tbnid=adrMsH2i7Zc0XM&vet=12ahUKEwjT0sGizob_AhVy0XMBHZJbD6IQMygAegUIARDjAQ..i&imgrefurl=https%3A%2F%2Fwww.dreamstime.com%2Fillustration%2Fcontribution.html&docid=-FJaMfa3q8X-EM&w=1300&h=1335&q=contributiion&ved=2ahUKEwjT0sGizob_AhVy0XMBHZJbD6IQMygAegUIARDjAQ)
          reactions: rocket
          pr_number: PR_NUMBER
    env:
      PR_NUMBER: ${{ github.event.number }}
