name: Commenting on pull request
on:
  pull_request:
    branches: [ "main" ]

jobs:
  comment_pr:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3

      - name: Accept PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: "Thank you @contributor_name for contributing. Your request will be accepted soon. ![](https://thumbs.dreamstime.com/z/contribute-d-word-pulled-up-team-giving-sharing-contribution-letters-working-together-donation-worthy-cause-47609276.jpg)"
          reactions: rocket
          pr_number: PR_NUMBER
    env:
      PR_NUMBER: ${{ github.event.number }}
