name: CI
on:
  pull_request:
    branches: [ "main" ]

jobs:
  comment_pr:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3

      - name: Accept PR
        uses: thollander/actions-comment-pull-request@v2
        if: ${{true}}
        with:
        #simulating tests, because there's nothing to test rn
          message: |
            PR correct, link to the issue if you haven't already and wait for merge.
          pr_number: PR_NUMBER

      - name: Deny PR
        uses: thollander/actions-comment-pull-request@v2
        if: ${{false}}
        with:
          message: |
            PR has flaws, fix them before I can accept.
          pr_number: PR_NUMBER
    env:
      PR_NUMBER: ${{ github.event.number }}
