name: Commenting on pull request
on:
  pull_request:
    branches: [ "main" ]

jobs:
  comment_pr:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3

      - name: Accept PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            Thank you for contributing. Your request will be accepted soon.
          reactions: rocket
          pr_number: PR_NUMBER
    env:
      PR_NUMBER: ${{ github.event.number }}
